package com.mindware.vista;

import com.mindware.domain.Usuario;
import com.mindware.services.UsuarioService;
import com.mindware.security.Encript;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;

import de.steinwedel.messagebox.MessageBox;

import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;

public class EditUsuario extends Window implements ClickListener{
	
	private AbsoluteLayout mainLayout;
	private HorizontalLayout horizontalLayout_4;
	private Button btncerrar;
	private Button btnguardar;
	private Label lbltitulo;
	private GridLayout gridLayout_1;
	private Label lblcampo6;
	private Label lblcampo5;
	private Label lblcampo4;
	private ComboBox cmbRol;
	private Label lblRol;
	private ComboBox cmbEstado;
	private Label lblEstado;
	private PasswordField txtPassword;
	private Label lblPassword;
	private TextField txtLogin;
	private Label lblLogin;
	private TextField txtNombre;
	private Label lblnombre;
	private String claveOriginal;
	private int usuarioId;
	
	public EditUsuario(Usuario usuario){
		buildMainLayout();
		setContent(mainLayout);
		postBuild();
		llenarDatos(usuario);
	}
	
	public void postBuild() {
		this.btnguardar.addClickListener((ClickListener)this);
		this.btncerrar.addClickListener((ClickListener)this);
	}
	
	public void llenarDatos(Usuario usuario) {
		cmbEstado.setValue(usuario.getEstado());
		txtLogin.setValue(usuario.getLogin());
		txtNombre.setValue(usuario.getNombre());
		txtPassword.setValue(usuario.getPassword());
		cmbRol.setValue(usuario.getRol());
		claveOriginal = usuario.getPassword();
		txtLogin.setReadOnly(true);
		usuarioId = usuario.getUsuarioId();
	}
	
	private boolean validaLogin(String login) {
		UsuarioService usuarioService = new UsuarioService();
		if (usuarioService.buscaLogin(login)==null) {
			return true;
		}
		else {
			return false;
		}
	}
	
	private boolean validarDatos(){
		if (txtLogin.isEmpty()) {return false;}
		if (txtNombre.isEmpty()) {return false;}
		if (txtPassword.isEmpty()) {return false;}
		if (cmbRol.isEmpty()) {return false;}
		if (cmbEstado.isEmpty()) {return false;}
		else {
			return true;
		}
	}
	
	@Override
	public void buttonClick(ClickEvent event) {
		if(event.getSource()==this.btnguardar) {
			if (validarDatos()) {
				
				guardar();
				
			} else {
				MessageBox.createError()
				.withCaption("Error")
				.withMessage("Revise los datos")
				.open();
			}
		}
	
		if(event.getSource()==this.btncerrar) {
			UI.getCurrent().removeWindow(this);
		}		
		
		
	}

	
	private void guardar(){
		UsuarioService usuarioService = new UsuarioService();
		Encript encript = new Encript();
		try {
			Usuario usuario = new Usuario();
			usuario.setEstado(cmbEstado.getValue().toString());
			usuario.setLogin(txtLogin.getValue());
			usuario.setNombre(txtNombre.getValue());
			if (claveOriginal==txtPassword.getValue()) {
				usuario.setPassword(txtPassword.getValue());
			}else {	
				usuario.setPassword(encript.encriptString(txtPassword.getValue()));
			}
			usuario.setRol(cmbRol.getValue().toString());
			usuario.setUsuarioId(usuarioId);
			usuarioService.updateUsuario(usuario);
			
			MessageBox.createInfo()
			.withCaption("Registro")
			.withMessage("Datos actualizados con exito!")
			.open();
			
		}
		catch (Exception e) {
			MessageBox.createError()
			.withCaption("Error ")
			.withMessage("Error: "+e)
			.open();
			
		}
	}
	
	
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("450px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("500px");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "top:70.0px;left:20.0px;");
		
		// lbltitulo
		lbltitulo = new Label();
		lbltitulo.setImmediate(false);
		lbltitulo.setWidth("-1px");
		lbltitulo.setHeight("-1px");
		lbltitulo.setValue("REGISTRO NUEVO USUARIO");
		mainLayout.addComponent(lbltitulo, "top:12.0px;left:210.0px;");
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4, "top:300.0px;left:38.0px;");
		
		return mainLayout;
	}
	
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("500px");
		gridLayout_1.setHeight("300px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(8);
		
		// lblnombre
		lblnombre = new Label();
		lblnombre.setImmediate(false);
		lblnombre.setWidth("-1px");
		lblnombre.setHeight("-1px");
		lblnombre.setValue("Nombre completo:");
		gridLayout_1.addComponent(lblnombre, 0, 0);
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setImmediate(false);
		txtNombre.setWidth("307px");
		txtNombre.setHeight("-1px");
		txtNombre.setRequired(true);
		txtNombre.setRequiredError("Nombre es requerido");
		
		gridLayout_1.addComponent(txtNombre, 1, 0);
		
		// lblLogin
		lblLogin = new Label();
		lblLogin.setImmediate(false);
		lblLogin.setWidth("-1px");
		lblLogin.setHeight("-1px");
		lblLogin.setValue("Login:");
		gridLayout_1.addComponent(lblLogin, 0, 1);
		
		// txtLogin
		txtLogin = new TextField();
		txtLogin.setImmediate(false);
		txtLogin.setWidth("307px");
		txtLogin.setHeight("-1px");
		//txtLogin.setReadOnly(true);
		gridLayout_1.addComponent(txtLogin, 1, 1);
		
		// lblPassword
		lblPassword = new Label();
		lblPassword.setImmediate(false);
		lblPassword.setWidth("-1px");
		lblPassword.setHeight("-1px");
		lblPassword.setValue("Password:");
		gridLayout_1.addComponent(lblPassword, 0, 2);
		
		// txtPassword
		txtPassword = new PasswordField();
		txtPassword.setImmediate(false);
		txtPassword.setWidth("307px");
		txtPassword.setHeight("-1px");
		txtPassword.setRequired(true);
		txtPassword.setRequiredError("Debe ingresar un password");
		gridLayout_1.addComponent(txtPassword, 1, 2);
		
		// lblEstado
		lblEstado = new Label();
		lblEstado.setImmediate(false);
		lblEstado.setWidth("-1px");
		lblEstado.setHeight("-1px");
		lblEstado.setValue("Estado:");
		gridLayout_1.addComponent(lblEstado, 0, 3);
		
		// cmbEstado
		cmbEstado = new ComboBox();
		cmbEstado.setImmediate(false);
		cmbEstado.setWidth("307px");
		cmbEstado.setHeight("-1px");
		cmbEstado.addItem("ACTIVO");
		cmbEstado.addItem("BAJA");
		gridLayout_1.addComponent(cmbEstado, 1, 3);
		
		// lblRol
		lblRol = new Label();
		lblRol.setImmediate(false);
		lblRol.setWidth("-1px");
		lblRol.setHeight("-1px");
		lblRol.setValue("Rol: ");
		gridLayout_1.addComponent(lblRol, 0, 4);
		
		// textField_9
		cmbRol = new ComboBox();
		cmbRol.setImmediate(false);
		cmbRol.setWidth("307px");
		cmbRol.setHeight("-1px");
		cmbRol.setRequired(true);
		cmbRol.setRequiredError("Seleccione un rol");
		cmbRol.addItem("admin");
		cmbRol.addItem("user");
		
		gridLayout_1.addComponent(cmbRol, 1, 4);
			
		
		return gridLayout_1;
	}
	
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("510px");
		horizontalLayout_4.setHeight("50px");
		horizontalLayout_4.setMargin(false);
		
		// btnguardar
		btnguardar = new Button();
		btnguardar.setCaption("Guardar");
		btnguardar.setImmediate(true);
		btnguardar.setWidth("120px");
		btnguardar.setHeight("-1px");
		horizontalLayout_4.addComponent(btnguardar);
		horizontalLayout_4.setComponentAlignment(btnguardar, new Alignment(20));
		
		// btncerrar
		btncerrar = new Button();
		btncerrar.setCaption("Cerrar");
		btncerrar.setImmediate(true);
		btncerrar.setWidth("120px");
		btncerrar.setHeight("-1px");
		horizontalLayout_4.addComponent(btncerrar);
		horizontalLayout_4.setComponentAlignment(btncerrar, new Alignment(20));
		
		return horizontalLayout_4;
	}

	
}

