package com.mindware.vista;

import com.mindware.domain.Usuario;
import com.mindware.security.Encript;
import com.mindware.services.UsuarioService;
//import com.mindware.scheduler.ListenerSms;
import com.mindware.smartsms.smsUI;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.server.ThemeResource;
import com.vaadin.event.ShortcutListener;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.themes.Reindeer;

import de.steinwedel.messagebox.MessageBox;

import com.vaadin.ui.Button.ClickEvent;


public class LoginUI extends CustomComponent implements ClickListener{

	/*- VaadinEditorProperties={"grid":"RegularGrid,8","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout borde;
	@AutoGenerated
	private NativeButton btnActualizarPassword;
	@AutoGenerated
	private NativeButton btnIngresar;
	@AutoGenerated
	private PasswordField txtClave;
	@AutoGenerated
	private TextField txtUsuario;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private Label label_5;
	private Label lblMensaje;
	private Usuario usuario;

	public LoginUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
        postBuild();
		
	}

	private void postBuild(){
		this.btnIngresar.addClickListener((ClickListener)this);
		this.btnActualizarPassword.addClickListener((ClickListener)this);
		this.txtUsuario.addShortcutListener(new ShortcutListener("",KeyCode.ENTER,null) {
			@Override
			public void handleAction(Object sender, Object target) {
				logeo();
			}
		} );

		this.txtClave.addShortcutListener(new ShortcutListener("",KeyCode.ENTER,null) {
			@Override
			public void handleAction(Object sender, Object target) {
				logeo();
			}
		});
	}

	private void logeo() {
		if (validarDatos()) {
//			if (this.txtUsuario.getValue().equals("admin") && this.txtClave.getValue().equals("123")) {
			if (validarCredenciales(txtUsuario.getValue(),txtClave.getValue())) {
				((smsUI) UI.getCurrent()).cargarMenu(usuario.getUsuarioId(), txtUsuario.getValue());
				
			} else {
				MessageBox.createWarning()
				.withCaption("Error")
				.withMessage("Credenciales incorrectas")
				.open();
			}
		}
	}

	private boolean validarCredenciales(String login, String password) {
		String loginDB;
		
		Encript encript = new Encript();
		
		UsuarioService usuarioService = new UsuarioService();
		usuario =  usuarioService.buscaLogin(login);
		if (usuario !=null) {
			if (encript.encriptString(password).equals(usuario.getPassword())) {
				return true;
			} else {
				return false;
			}
		} else {
			return false;
		}
		
		
	}
	
	private boolean validarDatos(){
		boolean respuesta=true;
		if(this.txtUsuario.getValue().toString().length()==0){
			this.lblMensaje.setValue("<b>Ingrese usuario</b>");
			return false;
		}else{
			this.lblMensaje.setValue("");
		}
		if(this.txtClave.getValue().toString().length()==0){
			this.lblMensaje.setValue("<b>Ingrese Clave</b>");
			return false;
		}else{
			this.lblMensaje.setValue("");
		}
		return respuesta;
	}
	@Override
	public void buttonClick(ClickEvent event ) {
		if (event.getSource()==this.btnIngresar) {
			logeo();
		}
		if (event.getSource()==this.btnActualizarPassword){
			if (txtUsuario.getValue().isEmpty()) {
				MessageBox.createError()
				.withCaption("Actualizar Password")
				.withMessage("Debe ingresar el Login")
				.open();
			} else {
				CambiarPassword cambiarPassword= new CambiarPassword(txtUsuario.getValue());
				cambiarPassword.setModal(true);
				cambiarPassword.setWidth("550px");
				cambiarPassword.setHeight("420px");
				cambiarPassword.center();
				UI.getCurrent().addWindow(cambiarPassword);
			}
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// borde
		borde = buildBorde();
		
		mainLayout.addComponent(borde, "top:180.0px;left:428.0px;");
		
	
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildBorde() {
		// common part: create layout
		borde = new AbsoluteLayout();
//		borde.setStyleName("Reindeer.LAYOUT_BLUE");
		borde.setImmediate(false);
		borde.setWidth("500px");
		borde.setHeight("282px");
//		borde.addStyleName("desktop");
//		borde.setStyleName("desktop");
	
//		//Login Panel
		Panel loginPanel = new Panel("<font size=4>Login<font>");//
		loginPanel.setStyleName("desktop");
		loginPanel.setCaptionAsHtml(true);
		
		AbsoluteLayout content = new AbsoluteLayout();//
		content.setWidth("420px");
		content.setHeight("222px");
//		borde.setSizeUndefined();
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Usuario:");
		
//		borde.addComponent(label_5, "top:0.0px;left:89.0px;");
		content.addComponent(label_5, "top:40.0px;left:89.0px;");
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Clave:");
//		borde.addComponent(label_6, "top:50.0px;left:102.0px;");
		content.addComponent(label_6, "top:90.0px;left:102.0px;");

		// lblMensaje
		lblMensaje = new Label();
		lblMensaje.setImmediate(false);
		lblMensaje.setWidth("-1px");
		lblMensaje.setHeight("-1px");
		lblMensaje.setValue("");
		lblMensaje.setContentMode(ContentMode.HTML);
//		borde.addComponent(lblMensaje, "top:90.0px;left:102.0px;");
		content.addComponent(lblMensaje, "top:130.0px;left:102.0px;");
				
		// txtUsuario
		txtUsuario = new TextField();
		txtUsuario.setImmediate(false);
		txtUsuario.setWidth("-1px");
		txtUsuario.setHeight("-1px");
//		borde.addComponent(txtUsuario, "top:0.0px;left:144.0px;");
		content.addComponent(txtUsuario, "top:40.0px;left:144.0px;");
		
		// txtClave
		txtClave = new PasswordField();
		txtClave.setImmediate(false);
		txtClave.setWidth("-1px");
		txtClave.setHeight("-1px");
//		borde.addComponent(txtClave, "top:50.0px;left:144.0px;");
		content.addComponent(txtClave, "top:90.0px;left:144.0px;");
		
		// btnIngresar
		btnIngresar = new NativeButton();
		btnIngresar.setCaption("<b>Ingresar<b>");
		btnIngresar.setCaptionAsHtml(true);
		btnIngresar.setImmediate(true);
		btnIngresar.setWidth("150px");
		btnIngresar.setHeight("30px");
		btnIngresar.setStyleName(Reindeer.BUTTON_LINK);
		btnIngresar.setIcon(new ThemeResource("../images/buttons/users.png"));
		
//		borde.addComponent(btnIngresar, "top:110.0px;left:150.0px;");
		content.addComponent(btnIngresar, "top:150.0px;left:60.0px;");
		
		
		// btnActualizarPassword
		btnActualizarPassword = new NativeButton();
		btnActualizarPassword.setCaption("<b>Cambiar Password<b>");
		btnActualizarPassword.setCaptionAsHtml(true);
		btnActualizarPassword.setImmediate(true);
		btnActualizarPassword.setWidth("150px");
		btnActualizarPassword.setHeight("30px");
		btnActualizarPassword.setStyleName(Reindeer.BUTTON_LINK);
		btnActualizarPassword.setIcon(new ThemeResource("../images/buttons/card-contact.png"));
		content.addComponent(btnActualizarPassword, "top:150.0px;left:230.0px;");
		
		loginPanel.setContent(content);
		loginPanel.setSizeUndefined();
		
		borde.addComponent(loginPanel);
		
		

		return borde;
	}

}
